"""
trivy_parser.py

Enterprise Trivy Parser

This parser converts Trivy JSON reports into the
framework's normalized Finding objects.

Responsibilities
----------------
✔ Parse Trivy JSON
✔ Normalize vulnerabilities
✔ Attach recommendations
✔ Extract CVSS
✔ Extract package information
✔ Extract fix information

Everything else is handled by BaseParser.
"""

from __future__ import annotations

from security.core.base_parser import BaseParser
from security.core.parser_registry import registry

from security.schemas.finding import Finding

from security.common.logger import logger
from security.common.metadata import generate_metadata
from security.common.recommendation import get_recommendation
from security.common.status import STATUS_OPEN
from security.common.categories import CATEGORY_CONTAINER
from security.common.scanner_type import SCANNER_STATIC

from security.config.config_loader import get


############################################################
# Configuration
############################################################

TOOL_NAME = "Trivy"

REPORT_DIR = get(
    "TRIVY",
    "report_dir"
)

OUTPUT_DIR = get(
    "TRIVY",
    "output_dir"
)


############################################################
# Trivy Parser
############################################################

class TrivyParser(BaseParser):

    """
    Enterprise Trivy Parser.

    BaseParser performs:

        ✔ Read report
        ✔ Validate report
        ✔ Metadata
        ✔ Statistics
        ✔ Report generation
        ✔ Save report
        ✔ Logging

    This parser only converts Trivy JSON into
    normalized Finding objects.
    """

    ########################################################
    # Constructor
    ########################################################

    def __init__(self):

        super().__init__(

            tool_name=TOOL_NAME,

            category=CATEGORY_CONTAINER,

            scanner_type=SCANNER_STATIC,

            input_directory=REPORT_DIR,

            output_directory=OUTPUT_DIR

        )

    ########################################################
    # Metadata Override
    ########################################################

    def build_metadata(self):

        """
        Extends the default metadata generated by
        BaseParser with Trivy-specific information.
        """

        metadata = generate_metadata(
            self.tool_name
        )

        metadata_section = self.raw_report.get(
            "Metadata",
            {}
        )

        os_info = metadata_section.get(
            "OS",
            {}
        )

        metadata.update({

            "artifact_name": self.raw_report.get(
                "ArtifactName"
            ),

            "artifact_type": self.raw_report.get(
                "ArtifactType"
            ),

            "artifact_id": self.raw_report.get(
                "ArtifactID"
            ),

            "image_id": metadata_section.get(
                "ImageID"
            ),

            "image_size": metadata_section.get(
                "Size"
            ),

            "operating_system": os_info.get(
                "Family"
            ),

            "operating_system_version": os_info.get(
                "Name"
            )

        })

        self.metadata = metadata

        return metadata

    ########################################################
    # Extract Findings
    ########################################################

    def extract_findings(self):

        findings = []

                ####################################################
        # Empty Report
        ####################################################

        if not self.raw_report:

            logger.warning(

                "Trivy report is empty."

            )

            return findings

        ####################################################
        # Scan Information
        ####################################################

        scan_time = self.raw_report.get(

            "CreatedAt",

            self.scan_time

        )

        ####################################################
        # Results
        ####################################################

        results = self.raw_report.get(

            "Results",

            []

        )

        ####################################################
        # Parse Every Result
        ####################################################

        for result in results:

            target = result.get(

                "Target"

            )

            target_class = result.get(

                "Class"

            )

            target_type = result.get(

                "Type"

            )

            vulnerabilities = result.get(

                "Vulnerabilities",

                []

            )

            ################################################
            # Parse Every Vulnerability
            ################################################

            for vulnerability in vulnerabilities:

                ############################################
                # Rule ID
                ############################################

                vulnerability_id = vulnerability.get(

                    "VulnerabilityID",

                    ""

                )

                ############################################
                # Severity
                ############################################

                severity = str(

                    vulnerability.get(

                        "Severity",

                        "UNKNOWN"

                    )

                ).upper()

                ############################################
                # Recommendation Database
                ############################################

                recommendation = get_recommendation(
                    TOOL_NAME,

                    vulnerability_id

                )

                ############################################
                # CVSS
                ############################################

                cvss_score = None

                cvss = vulnerability.get(

                    "CVSS",

                    {}

                )

                for vendor in cvss.values():

                    if vendor.get("V3Score"):

                        cvss_score = vendor.get(

                            "V3Score"

                        )

                        break

                    if vendor.get("V2Score"):

                        cvss_score = vendor.get(

                            "V2Score"

                        )

                        break

                ############################################
                # References
                ############################################

                references = vulnerability.get(

                    "References",

                    []

                )

                primary_reference = (

                    references[0]

                    if references

                    else None

                )

                ############################################
                # Build Finding
                ############################################

                finding = Finding(

                    ################################################
                    # Framework
                    ################################################

                    tool=TOOL_NAME,

                    category=CATEGORY_CONTAINER,

                    ################################################
                    # Rule
                    ################################################

                    rule_id=vulnerability_id,

                    ################################################
                    # Severity
                    ################################################

                    severity=severity,

                    ################################################
                    # Location
                    ################################################

                    file=target,

                    line=None,

                    ################################################
                    # Description
                    ################################################

                    message=(

                        vulnerability.get("Title")

                        or

                        vulnerability.get("Description")

                    ),

                    ################################################
                    # Recommendation
                    ################################################

                    recommendation=recommendation,

                    ################################################
                    # Runtime
                    ################################################

                    status=STATUS_OPEN,

                    scan_time=scan_time,

                    ################################################
                    # Package
                    ################################################

                    package_name=vulnerability.get(

                        "PkgName"

                    ),

                    installed_version=vulnerability.get(

                        "InstalledVersion"

                    ),

                    fixed_version=vulnerability.get(

                        "FixedVersion"

                    ),

                    ################################################
                    # CVE
                    ################################################

                    cve=vulnerability_id,

                    cwe=None,

                    cvss_score=cvss_score,

                    severity_source=vulnerability.get(

                        "SeveritySource"

                    ),

                    ################################################
                    # Resource
                    ################################################

                    target=target,

                    target_class=target_class,

                    target_type=target_type,

                    ################################################
                    # Documentation
                    ################################################

                    description=vulnerability.get(

                        "Description"

                    ),

                    primary_url=primary_reference,

                    references=references,

                    ################################################
                    # Future
                    ################################################

                    exploit_available=False,

                    fix_available=bool(

                        vulnerability.get(

                            "FixedVersion"

                        )

                    ),

                    compliance=[],

                    epss_score=None,

                    kev=False

                )

                ############################################
                # Add Finding
                ############################################

                findings.append(

                    finding

                )

        ####################################################
        # Finished
        ####################################################

        logger.info(

            f"Parsed {len(findings)} Trivy findings."

        )

        return findings
        ########################################################
    # Lifecycle Hook
    ########################################################

    def before_parse(self):
        """
        Executed before parsing starts.

        Future Uses
        -----------
        • Load rule cache
        • Initialize CVE database
        • Connect to database
        • Download KEV feed
        """

        logger.info(

            f"[{TOOL_NAME}] Preparing parser..."

        )

    ########################################################
    # Lifecycle Hook
    ########################################################

    def after_parse(self):
        """
        Executed after parsing completes.

        Future Uses
        -----------
        • Push findings to database
        • Export HTML/PDF
        • Send Slack notifications
        • Upload to Dashboard
        """

        logger.info(

            f"[{TOOL_NAME}] Parser completed."

        )


############################################################
# Register Parser
############################################################

registry.register(

    "trivy",

    TrivyParser

)


############################################################
# Main
############################################################

def main():

    logger.info("=" * 70)

    logger.info(

        "Starting Trivy Parser"

    )

    logger.info("=" * 70)

    parser = TrivyParser()

    parser.run()


if __name__ == "__main__":

    main()
